### ISSUE TITLE
PEG.js 0.9.0

### ISSUE THREAD

**Issue by felixhao28** [dvberkel/grunt-peg#18]
Please update the dependency.

Also Coffeescript is not used or featured in this package anywhere. So I think it makes more sense to remove the dependency of pegjs-coffee-plugin by adding a self-written plugin for testing purpose.

**Comment by felixhao28** [comment]
I created a pr to fix this, pls have a look.

**Comment by dvberkel** [comment]
@felixhao28 thanks for the time to submit a pull request. I will review your submission and will get back to you this evening

**Comment by dvberkel** [comment]
@felixhao28 Thanks for your contribution, it is merged into master. I will release a new version to npm soon
